// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdvPC40dn7JzV4oP50yS5fvJfGugvoZOo',
    appId: '1:156302186694:web:119555381068a8c5091fc7',
    messagingSenderId: '156302186694',
    projectId: 'civvys-8e5f1',
    authDomain: 'civvys-8e5f1.firebaseapp.com',
    storageBucket: 'civvys-8e5f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB02ov5XMHBwp1Qkzto_9VSEfcduNzfDCM',
    appId: '1:156302186694:android:759a2f7db1098c6a091fc7',
    messagingSenderId: '156302186694',
    projectId: 'civvys-8e5f1',
    storageBucket: 'civvys-8e5f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ2VgTr5Dzlq5F9SfPHIqUWpyCGYk6eoI',
    appId: '1:156302186694:ios:8c4c4a14f3b4423a091fc7',
    messagingSenderId: '156302186694',
    projectId: 'civvys-8e5f1',
    storageBucket: 'civvys-8e5f1.appspot.com',
    iosClientId:
        '156302186694-4med2hpp3fm2487njbm5073ttu8jfmng.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourthing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ2VgTr5Dzlq5F9SfPHIqUWpyCGYk6eoI',
    appId: '1:156302186694:ios:8c4c4a14f3b4423a091fc7',
    messagingSenderId: '156302186694',
    projectId: 'civvys-8e5f1',
    storageBucket: 'civvys-8e5f1.appspot.com',
    iosClientId:
        '156302186694-4med2hpp3fm2487njbm5073ttu8jfmng.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourthing',
  );
}
